# SPDX-License-Identifier: GPL-3.0-or-later
from __future__ import annotations

import json
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from tilejoin_config import (  # noqa: E402
    ConfigOptions,
    Output,
    auto_pair,
    candidate_diagnostics,
    choose_common_modes,
    config_for,
    member_positions,
    parse_outputs,
    select_outputs,
    selectors_for,
)


def output(
    connector: str,
    *,
    x: int,
    y: int,
    width: int = 1920,
    height: int = 1080,
    scale: float = 1.0,
    transform: str = "normal",
    make: str = "Example",
    model: str = "Panel",
    serial: str | None = None,
    refresh: int = 60000,
    modes: tuple[dict[str, object], ...] | None = None,
) -> Output:
    transformed = (height, width) if transform in {"90", "270"} else (width, height)
    mode = {"width": width, "height": height, "refresh_rate": refresh}
    return Output(
        connector=connector,
        make=make,
        model=model,
        serial=serial,
        mode=mode,
        modes=tuple(modes) if modes is not None else (mode,),
        transform=transform,
        scale=scale,
        logical={
            "x": x,
            "y": y,
            "width": round(transformed[0] / scale),
            "height": round(transformed[1] / scale),
            "scale": scale,
            "transform": transform,
        },
        physical_size=None,
    )


class TilejoinConfigTests(unittest.TestCase):
    def test_portrait_pair_preserves_current_physical_positions(self) -> None:
        fixture = json.loads((ROOT / "tests/fixtures/portrait-outputs.json").read_text())
        outputs = parse_outputs(fixture)
        selected = select_outputs(outputs, ["DVI-I-1", "DVI-I-2"])

        self.assertEqual(member_positions(selected), [(2160, 0), (0, 0)])
        config = config_for(selected, ConfigOptions(name="portrait-wall"))
        self.assertTrue(config.startswith("// Generated by niri-tilejoin; config-schema=1\n"))
        self.assertIn('member "DVI-I-1" {', config)
        self.assertIn("position x=2160 y=0", config)
        self.assertIn('member "LG Electronics LG ULTRAFINE 0x01010101" {', config)
        self.assertIn("position x=0 y=0", config)
        self.assertIn('primary "DVI-I-1"', config)

    def test_vertical_layout_is_preserved(self) -> None:
        outputs = [
            output("A", x=0, y=1080, serial="A"),
            output("B", x=0, y=0, serial="B"),
        ]
        self.assertEqual(member_positions(outputs), [(0, 1080), (0, 0)])

    def test_gap_is_rejected(self) -> None:
        outputs = [output("A", x=0, y=0), output("B", x=2000, y=0)]
        with self.assertRaisesRegex(ValueError, "rectangular physical area"):
            member_positions(outputs)

    def test_unequal_scales_are_rejected(self) -> None:
        outputs = [output("A", x=0, y=0), output("B", x=1920, y=0, scale=1.25)]
        with self.assertRaisesRegex(ValueError, "different scales"):
            member_positions(outputs)

    def test_duplicate_stable_selectors_fall_back_to_connectors(self) -> None:
        outputs = [
            output("A", x=0, y=0, serial="same"),
            output("B", x=1920, y=0, serial="same"),
        ]
        self.assertEqual(selectors_for(outputs), ["A", "B"])

    def test_selector_uniqueness_uses_all_discovered_outputs(self) -> None:
        selected = [
            output("A", x=0, y=0, serial="same"),
            output("B", x=1920, y=0, serial="unique"),
        ]
        unselected = output("C", x=4000, y=0, serial="same")
        self.assertEqual(
            selectors_for(selected, [*selected, unselected]),
            ["A", "Example Panel unique"],
        )

    def test_strict_refresh_accepts_five_millihertz_not_six(self) -> None:
        five = [
            output("A", x=0, y=0, refresh=60000),
            output("B", x=1920, y=0, refresh=59995),
        ]
        six = [
            output("A", x=0, y=0, refresh=60000),
            output("B", x=1920, y=0, refresh=59994),
        ]
        self.assertIsNotNone(choose_common_modes(five, False))
        self.assertIsNone(choose_common_modes(six, False))

    def test_relaxed_refresh_accepts_one_hundred_millihertz_not_one_hundred_one(
        self,
    ) -> None:
        hundred = [
            output("A", x=0, y=0, refresh=60000),
            output("B", x=1920, y=0, refresh=59900),
        ]
        hundred_one = [
            output("A", x=0, y=0, refresh=60000),
            output("B", x=1920, y=0, refresh=59899),
        ]
        self.assertIsNotNone(choose_common_modes(hundred, True))
        self.assertIsNone(choose_common_modes(hundred_one, True))

    def test_alternate_current_resolution_mode_can_supply_common_refresh(self) -> None:
        preferred: dict[str, object] = {
            "width": 3840,
            "height": 2160,
            "refresh_rate": 59997,
            "is_preferred": True,
        }
        alternate: dict[str, object] = {
            "width": 3840,
            "height": 2160,
            "refresh_rate": 60000,
        }
        left = output(
            "A",
            x=0,
            y=0,
            width=3840,
            height=2160,
            refresh=59997,
            modes=(preferred, alternate),
        )
        right = output("B", x=3840, y=0, width=3840, height=2160, refresh=60000)
        selected = choose_common_modes([left, right], False)
        self.assertIsNotNone(selected)
        assert selected is not None
        self.assertEqual([item.mode["refresh_rate"] for item in selected], [60000, 60000])

    def test_unique_touching_pair_is_auto_selected(self) -> None:
        pair = [output("A", x=0, y=0), output("B", x=1920, y=0)]
        self.assertEqual(auto_pair(pair), pair)

    def test_ambiguous_touching_pairs_require_explicit_choice(self) -> None:
        outputs = [
            output("A", x=0, y=0),
            output("B", x=1920, y=0),
            output("C", x=3840, y=0),
        ]
        with self.assertRaisesRegex(SystemExit, "multiple compatible pairs"):
            auto_pair(outputs)

    def test_explicit_connectors_must_be_unique(self) -> None:
        with self.assertRaisesRegex(SystemExit, "must be unique"):
            select_outputs([output("A", x=0, y=0)], ["A", "A"])

    def test_diagnostics_explain_refresh_geometry_and_selector_fallback(self) -> None:
        outputs = [
            output("A", x=0, y=0, serial="same", refresh=60000),
            output("B", x=1920, y=0, serial="same", refresh=59995),
            output("C", x=5000, y=0, serial="other", refresh=59000),
        ]
        diagnostics = candidate_diagnostics(outputs)
        self.assertIn(
            "accept A+B; duplicate EDID identity, using connector selector for A, B",
            diagnostics,
        )
        self.assertTrue(
            any(line.startswith("reject A+C: no common strict") for line in diagnostics)
        )


if __name__ == "__main__":
    unittest.main()
